apiVersion: amd.com/v1alpha1
kind: DeviceConfig
metadata:
  name: amd-gpu
  namespace: amd-gpu-operator
spec:
  devicePlugin:
    enableNodeLabeller: true
    devicePluginImage: {{ .Values.config.devicePlugin.image }}
    nodeLabellerImage: {{ .Values.config.nodeLabeller.image }}
  driver:
    enable: true
    version: {{ .Values.config.rocmVersion }}
  selector:
    feature.node.kubernetes.io/amd-gpu: 'true'