apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "10"
  name: job-confirm-amd-gpu-present
spec:
  template:
    spec:
      containers:
        - image: {{ .Values.amdcheckjob.image }}
          command:
            - /bin/bash
            - -c
            - |
               cat
          imagePullPolicy: IfNotPresent
          name: confirm-amd-gpu-present
          resources:
            limits:
              amd.com/gpu: "1"
            requests:
              amd.com/gpu: "1"
      restartPolicy: Never
      serviceAccount: {{ .Values.serviceAccountName }}
      serviceAccountName: {{ .Values.serviceAccountName }}
