---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  annotations:
    haproxy.router.openshift.io/timeout: 86400s # long timeout for dataprep processing
  name: {{ .Values.global.amdllm.service_name }}-microservice-route
  namespace: {{ .Values.global.amdllm.namespace }}
spec:
  host: megaservice-{{ .Values.global.amdllm.namespace }}.apps.{{ .Values.global.clusterDomain }}
  path: /v1/dataprep
  port:
    targetPort: {{ .Values.global.amdllm.service_port }}
  to:
    kind: Service
    name: {{ .Values.global.amdllm.service_name }}
    weight: 100
  wildcardPolicy: None
