---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  # TODO(SG): Provide the correct keyword for AMD
  name: tei
  namespace: {{ .Values.global.amdllm.namespace }}
spec:
  lookupPolicy:
    local: true
