---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ .Values.global.amdllm.service_name }}-main-route
  namespace: {{ .Values.global.amdllm.namespace }}
spec:
  host: megaservice-{{ .Values.global.amdllm.namespace }}.apps.{{ .Values.global.clusterDomain }}
  port:
    targetPort: {{ .Values.global.amdllm.service_port }}
  to:
    kind: Service
    name: {{ .Values.global.amdllm.service_name }}
    weight: 100
  wildcardPolicy: None
