global: 
  pattern: amd_llm

  clusterDomain: igk.internal

  amdllm:
    namespace: amd-llm
    build_envs: [] # http_proxy/https_prxy can be set here
    runtime_envs: []
    
    chatqna_amd_backend:
      git_ref: 7c2e7f6
      image: image-registry.openshift-image-registry.svc:5000/opea/chatqna:latest
      megaservice_envs:
        - name: EMBEDDING_SERVICE_HOST_IP
          value: embedding.amd-llm.svc.cluster.local
        - name: EMBEDDING_SERVICE_PORT
          value: '"6000"'
        - name: RETRIEVER_SERVICE_HOST_IP 
          value: retriever.amd-llm.svc.cluster.local
        - name: RETRIEVER_SERVICE_PORT 
          value: '"7000"'
        - name: RERANK_SERVICE_HOST_IP 
          value: reranking.amd-llm.svc.cluster.local
        - name: RERANK_SERVICE_PORT
          value: '"8000"'
        - name: LLM_SERVICE_HOST_IP 
          value: llm.amd-llm.svc.cluster.local
        - name: LLM_SERVICE_PORT 
          value: '"9000"'
