---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: rerank-microservice-route
  namespace: {{ .Values.global.amdllm.namespace }}
spec:
  host: megaservice-{{ .Values.global.amdllm.namespace }}.apps.{{ .Values.global.clusterDomain }}
  path: /v1/reranking
  port:
    targetPort: 8000
  to:
    kind: Service
    name: {{ .Values.global.amdllm.service_name }}
    weight: 100
  wildcardPolicy: None
