config:
   devicePlugin:
     image: rocm/k8s-device-plugin:latest
   nodeLabeller:
     image: rocm/k8s-device-plugin:labeller-latest
   rocmVersion: 6.2.2 # pinned @ 6.2.2 because of https://github.com/ROCm/gpu-operator/issues/66

amdcheckjob:
  image: redhat/ubi9-minimal:latest

machineconfigName:
  fwpath: 99-worker-kernel-args-firmware-path

job:
  image: image-registry.openshift-image-registry.svc:5000/openshift/cli:latest
  namespace: amd-gpu-operator

serviceAccountName: mcp-amd-config-sa
rbac:
  roles:
    - name: amd-config-role
      createRole: true
      apiGroups:
        - '""'
        - '"apps"'
        - '"apiextensions.k8s.io"'
        - '"machineconfiguration.openshift.io"'
        - '"imageregistry.operator.openshift.io"'
      scope:
        cluster: true
      resources:
        - machineconfigs
        - machineconfigpools
        - pods
        - namespaces
        - services
        - configs
      verbs:
        - "get"
        - "list"
        - "patch"
        - "update"
        - "create"
        - "watch"
  roleBindings:
    - name: amd-config-rolebinding
      createBinding: true
      scope:
        cluster: true
        namespace: ""
      subjects:
        kind: ServiceAccount
        name: mcp-amd-config-sa
        namespace: amd-gpu-operator
        apiGroup: ""
      roleRef:
        kind: ClusterRole
        name: amd-config-role
