global: 
  pattern: amdllm

  amdllm:
    namespace: amd-llm
    build_envs: [] # http_proxy/https_prxy can be set here
    runtime_envs: []

    service_name: embedding
    image: quay.io/sgahlot/opea/embedding:latest
      # git_ref: 7c2e7f6 # make sure to validate buildconfig & other change scope before updating

    tei_service:
      name: tei-service
      port: 8091
