apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker_compose.yaml
    kompose.version: 1.33.0 (3ce457399)
    argocd.argoproj.io/sync-wave: "5"
    image.openshift.io/triggers: '[{"from":{"kind":"ImageStreamTag","name":"{{ .Values.global.amdllm.service_name }}:latest"},"fieldPath":"spec.template.spec.containers[?(@.name==\"{{ .Values.global.amdllm.service_name }}-server\")].image"}]'
  labels:
    io.kompose.service: {{ .Values.global.amdllm.service_name }}
  name: {{ .Values.global.amdllm.service_name }}
  namespace: {{ .Values.global.amdllm.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: {{ .Values.global.amdllm.service_name }}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker_compose.yaml
        kompose.version: 1.33.0 (3ce457399)
      labels:
        io.kompose.network/chatqna-default: "true"
        io.kompose.service: {{ .Values.global.amdllm.service_name }}
    spec:
      containers:
        - env:
            - name: {{ .Values.global.amdllm.env.home.name }}
              value: {{ .Values.global.amdllm.env.home.value }}
            - name: {{ .Values.global.amdllm.env.python.name }}
              value: {{ .Values.global.amdllm.env.python.value }}
            - name: {{ .Values.global.amdllm.env.rag.name }}
              value: {{ .Values.global.amdllm.env.rag.value }}
            - name: {{ .Values.global.amdllm.env.redis.name }}
              value: {{ .Values.global.amdllm.env.redis.value }}
            {{- if .Values.global.amdllm.runtime_envs }}
            {{- range .Values.global.amdllm.runtime_envs }}
            - name: {{ .name }}
              value: {{ .value }}
            {{- end }}
            {{- end }}
          image: {{ .Values.global.amdllm.image }}
          name: {{ .Values.global.amdllm.service_name }}-server
          ports:
            - containerPort: {{ .Values.global.amdllm.container_port }}
              protocol: TCP
          workingDir: {{ .Values.global.amdllm.working_dir }}
          volumeMounts:
            - name: {{ .Values.global.amdllm.volume.tmp.name }}
              mountPath: {{ .Values.global.amdllm.volume.tmp.path }}
      restartPolicy: Always
      volumes:
        - name: {{ .Values.global.amdllm.volume.tmp.name }}
          emptyDir: {}
