global: 
  pattern: amdllm

  amdllm:
    namespace: amd-llm
    build_envs: [] # http_proxy/https_prxy can be set here
    runtime_envs: []

    service_name: reranking

    image: quay.io/sgahlot/opea/reranking:latest
    # git_ref: 7c2e7f6 # make sure to validate buildconfig & other change scope before updating

    secret:
      env_name: HUGGINGFACEHUB_API_TOKEN
      name: hf-token-secret
      key: huggingface

    tei_service:
      name: tei-reranker-service
      port: 8090

