global: 
  pattern: amdllm

  amdllm:
    namespace: amd-llm
    build_envs: [] # http_proxy/https_prxy can be set here
    runtime_envs: []

    reranking:  
      image: quay.io/sgahlot/opea/reranking:latest
      # git_ref: 7c2e7f6 # make sure to validate buildconfig & other change scope before updating

    tei_service:
      name: tei-xeon-service
      port: 8080
      # port: 8090

