apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: {{ .Values.global.amdllm.service.name }}-claim0
  name: {{ .Values.global.amdllm.service.name }}-claim0
  namespace: {{ .Values.global.amdllm.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.global.amdllm.service.pvc.size }}
