kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: chatqna-ui-server
  namespace: {{ .Values.global.amdllm.namespace }}
spec:
  output:
    to:
      kind: "ImageStreamTag"
      name: "chatqna-ui:latest"
  failedBuildsHistoryLimit: 5
  successfulBuildsHistoryLimit: 5
  nodeSelector: null
  postCommit: {}
  resources: {}
  runPolicy: SerialLatestOnly
  source:
    contextDir: ChatQnA/ui
    git:
      ref: {{ .Values.global.amdllm.chatqna_ui_server.git_ref }}
      uri: https://github.com/opea-project/GenAIExamples.git
    type: Git
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: docker/Dockerfile
      {{- if .Values.global.amdllm.build_envs }}
      env:
      {{- range .Values.global.amdllm.build_envs }}
      - name: {{ .name }}
        value: {{ .value }}
      {{- end }}
      {{- end }}
  triggers:
  - type: ConfigChange
