global: 
  pattern: amdllm

  clusterDomain: lab.com

  amdllm:
    namespace: amd-llm
    build_envs: [] # http_proxy/https_prxy can be set here
    runtime_envs: []
    
    chatqna_ui_server:
      git_ref: 61a8bef
      image: image-registry.openshift-image-registry.svc:5000/opea/chatqna-ui:latest
